### PR TITLE
show past and future family separation events with different icons

### PR DESCRIPTION
**Pull request by dryan**

### CODE REVIEW

**Comment by dryan** [comment]
I think the gray star might be too dark.

**Review by jillh510 — COMMENTED** [review]
I agree the gray is way too dark. Looks black.

**Comment by marionnewlevant** [comment]
Curious about how this pull request relates to mine #42.

**Comment by dryan** [comment]
@marionnewlevant we can use your code, I was mostly just testing the new images on the sprite. The new names are 'star-blue' and 'star-gray-light' respectively.

**Pull request closed without merging**
